# Global constant definitions

import os

# Indicates whether we're in a local test environment or not.
LOCAL_TEST = os.getenv('LOCAL_TEST', None) is not None

# Dimensions of the images that will be used for classification and training.
WIDTH = 224
HEIGHT = 224

# Flags passed to ImageMagick to convert DICOMs to PNGs. This should be
# kept in sync with the variable in preprocess.sh.
IMAGE_MAGICK_FLAGS = '-depth 8 -resize {}x{}! -colorspace sRGB'.format(WIDTH, HEIGHT)

DIR_PREFIX = '../..' if LOCAL_TEST else ''

# Directory where raw .dcm training images are stored according to challenge guidelines.
# Available to the docker training image.
TRAINING_IMG_DIR = DIR_PREFIX + '/trainingData'

# Directory where raw .dcm inference images are stored according to challenge guidelines.
# Available to the docker scoring image.
INFERENCE_IMG_DIR = DIR_PREFIX + '/inferenceData'

# Directory where preprocessed data can be saved according to challenge guidelines.
# Not available to the docker scoring image.
PREPROCESS_DIR = DIR_PREFIX + '/preprocessedData'

# Directory where preprocessed images are stored.
PREPROCESS_IMG_DIR = PREPROCESS_DIR + '/images'

# Location where exams_metadata.tsv is stored according to challenge guidelines.
# Not available for Sub-Challenge 1.
EXAMS_METADATA_FILEPATH = DIR_PREFIX + '/metadata/exams_metadata.tsv'
# Location where images_crosswalk.tsv is stored according to challenge guidelines.
IMAGES_CROSSWALK_FILEPATH = DIR_PREFIX + '/metadata/images_crosswalk.tsv'

# Location to save the trained model according to challenge guidelines.
MODELSTATE_DIR = DIR_PREFIX + '/modelState'

# Name of the trained model file.
MODEL_FILENAME = 'trained.h5'

# File containing scores generated by trained model.
OUTPUT_FILEPATH = DIR_PREFIX + '/output/predictions.tsv'
