FROM tschaffter/keras-gpu
MAINTAINER Thomas Schaffter <thomas.schaffter@gmail.com>

# Install dependencies for image preprocessing
RUN yum makecache fast
RUN yum install -y perl \
    wget \
    ImageMagick

# Install GNU Parallel
RUN wget http://repo.openfusion.net/centos7-x86_64/parallel-20160622-1.of.el7.x86_64.rpm && \
	rpm -Uvh parallel-20160622-1.of.el7.x86_64.rpm && rm -fr parallel-20160622-1.of.el7.x86_64.rpm

WORKDIR /
COPY requirements.txt .
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

COPY preprocess/generate_image_labels.py .
COPY preprocess/preprocess.sh .
COPY score/sc1_infer.sh .
COPY score_mammo_vgg.py .
COPY utils /utils
