FROM tschaffter/keras-gpu
MAINTAINER James Yuan <jamesj.yuan@mail.utoronto.ca>

RUN pip install --upgrade pip
RUN pip install Pillow
RUN pip install --upgrade keras

WORKDIR /
COPY train/train.sh .
COPY train_mammo_vgg.py .
COPY models /models
COPY utils /utils
