FROM tschaffter/keras-gpu
MAINTAINER James Yuan <jamesj.yuan@mail.utoronto.ca>

WORKDIR /
COPY train/train.sh .
COPY train_mammo_vgg.py .
COPY models /models
COPY utils /utils
COPY requirements.txt .

RUN pip install --upgrade pip
RUN pip install -r requirements.txt

