FROM tschaffter/keras-gpu
MAINTAINER Thomas Schaffter <thomas.schaffter@gmail.com>

RUN yum install -y perl \
    wget \
    ImageMagick

WORKDIR /
COPY requirements.txt .
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

COPY score/sc1_infer.sh .
COPY score_mammo.py .
COPY utils /utils
